### ISSUE TITLE
trailing whitespace

### ISSUE THREAD

**Issue by zenspider** [Bruce-Connor/aggressive-indent-mode#38]
I've got "whitespace" mode on globally pointing out my trailing whitespace, mixes of tabs/spaces, etc. `aggressive-indent` will force indentation to exist even if I use something like `delete-traliing-whitespace`. Can there be an option to NOT add indentation if it just ends in a newline? I looked at the code and couldn't figure out the right place to patch this.

**Comment by Bruce-Connor** [comment]
Hi there. 
So you still have this problem? Or can I consider this issue solved?
