### ISSUE TITLE
aggressive-indent-mode is quietly disabled in cc-mode based modes in emacs 24.4+

### ISSUE THREAD

**Issue by davidshepherd7** [Bruce-Connor/aggressive-indent-mode#39]
Since emacs 24.4 cc-mode [sets electric-indent-inhibit by default](
https://github.com/emacs-mirror/emacs/blob/master/lisp/progmodes/cc-mode.el#L592), which combined with [this commit](https://github.com/Bruce-Connor/aggressive-indent-mode/commit/76c10dac8256d12fc9906e9c732fce3c2098c4af) cripples aggressive-indent-mode in many programming modes. I say cripples because the mode is still enabled but doesn't do anything (which was quite confusing).

[Here's the emacs commit in question, in case that's useful.](https://github.com/emacs-mirror/emacs/commit/29238d289dc33b70059bdfd82588db84254004a1)

I don't have any useful ideas for how to get around this sorry. Personally I've just reverted the aggressive-indent-mode commit that checks `electric-indent-inhibit` to get it working again.

**Comment by Bruce-Connor** [comment]
Gah, that's depressing. `electric-indent-inhibit` is supposed to be used by modes where automatic indentation does not make sense. It's a shame `cc-mode` decided use it. :-(

I'll revert that commit, and not rely on this variable anymore.
