### ISSUE TITLE
Option to align columns in a clojure let?

### ISSUE THREAD

**Issue by chenglou** [Bruce-Connor/aggressive-indent-mode#40]
Would it be possible to have this?

```clojure
(let [longName 1
      y        2])
```

Currently the `2` isn't aligned to `1`. Would be nice to optionally have it aligned. Though I'm not sure of the implication of this feature on the rest of the features.

**Comment by Bruce-Connor** [comment]
Yes and no.

Aggressive-indent cannot do that. It doesn't actually handle any fancy indentation. It just calls `indent-region`, which performs whatever indentation is defined by the major mode. 

You can technically do that, by changing the way that clojure-mode does indentation. If you can hack clojure mode to perform this vertical alignment when you hit TAB, then aggressive-indent-mode will automatically pick up this behaviour.

**Comment by chenglou** [comment]
Makes sense. Thanks!
