### ISSUE TITLE
dont-indent-if hooks appear to be broken

### ISSUE THREAD

**Issue by davidshepherd7** [Bruce-Connor/aggressive-indent-mode#41]
I think the quoting in `(eval (cons 'or dont-indent-if))` on [this line](https://github.com/Bruce-Connor/aggressive-indent-mode/blob/master/aggressive-indent.el#L248) is broken, I can't get hooks in `aggressive-indent-dont-indent-if` to work correctly.

Here's a [stripped down version of the problematic code](https://gist.github.com/davidshepherd7/d9b99d7762ca796d3501):
```elisp
(defun true1 () t)
(setq function-list (list #'true1))
(cons 'or function-list)
(eval (cons 'or function-list)) 
``` 
for me the `cons` line returns `(or true1 true2)`, but the `eval` line gives the error `(void-variable true1)`.

In the real code this error is trapped by a `condition-case` which tells me that there's an error in my hook function (confusing!). Maybe the error handling should be moved "inside" the `or` function so that it only catches errors in the hook functions?

[In case it's relevant: I'm using emacs24.4 from the tagged version in the git repo, aggressive-indent is from melpa: Version: 20150115.1200]

**Comment by Bruce-Connor** [comment]
Hi there. Thanks for filing this. 

The reason you're getting this error is that the `dont-indent-if` variable is not a hook, so adding functions to it doesn't work (and it's not supposed to). 
This variable is actually a list of *expressions*, so you need to add expressions to it. 

I'm at my phone right now, so it's complicated to write a code example for you. But I'll write one as soon as I can. 
Some of the closed issues here have usage examples for this variable. You can also look at the `internal-` version of this variable, which comes populated with a few expressions.

**Comment by davidshepherd7** [comment]
Haha I feel like an idiot but I understand now, thanks.

**Comment by Bruce-Connor** [comment]
Not at all, it's a very unusual approach that I took here. But I like how it turned out, I think it's faster to add an expression than a function.
